
# configuration.yaml

api:
  base_url: https://your-api-url.com
  key: your-api-key

commission:
  user_percent: 1.0  # Customer commission %
  owner_percent: 1.5 # Owner commission %

features:
  referral_enabled: true
  ads_enabled: true
  upi_withdrawal: true
